"""Multi-agent panel prompt templates."""

# Import prompt templates
from .cognitive_diversity_panel import (
    FIRST_PRINCIPLES_AGENT_PROMPT,
    INVERSION_THINKER_AGENT_PROMPT,
    SYSTEMS_DYNAMICS_AGENT_PROMPT,
    OPPORTUNITY_COST_AGENT_PROMPT,
    DECISION_JOURNAL_AGENT_PROMPT,
    SYNTHESIS_NODE_PROMPT,
    COGNITIVE_ROUTER_PROMPT
)

from .decision_intelligence_panel import (
    DECISION_CLASSIFIER_PROMPT,
    OPTIONS_GENERATOR_PROMPT,
    CRITERIA_DEFINER_PROMPT,
    PROBABILITY_ASSESSOR_PROMPT,
    CONSEQUENCE_MAPPER_PROMPT,
    DECISION_EVALUATION_PROMPT,
    FINAL_RECOMMENDATION_PROMPT
)

from .future_scenario_panel import (
    TREND_ANALYZER_PROMPT,
    SCENARIO_GENERATOR_PROMPT,
    OPPORTUNITY_EXPLORER_PROMPT,
    THREAT_ANALYZER_PROMPT,
    ROBUST_STRATEGY_DEVELOPER_PROMPT,
    SCENARIO_SYNTHESIS_PROMPT
) 